version: '3.2'
services:
  lizmap:
    image: jancelin/docker-lizmap:3.1.11
    restart: on-failure
    ports:
     - 80:80
     - 443:443
    volumes:
     - project:/home
     - var:/var/www/websig/lizmap/var
    depends_on:
      - postgis
      - qgiserver
      - redis
    links:
     - qgiserver:qgiserver
     - redis:redis
     
  qgiserver:
    image: jancelin/qgis-server:2.18LTR
    restart: on-failure
    volumes:
      - project:/home
    expose:
      - 80
      
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis:/data
    expose:
      - 6379

  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    expose:
      - 5432
    command: >
      bash -c "wget -P /home https://raw.githubusercontent.com/jancelin/docker-postgis/master/start-postgis.sh &&
               wget -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.sql &&
               chmod +x /home/start-postgis.sh &&
               sh /home/start-postgis.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.sql
      
  pgadmin4:
    image: chorss/docker-pgadmin4
    restart: on-failure
    ports:
      - 5050:5050
    volumes:
      - pgadmin4:/data
      
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer:/data
     
  cloud:
    image: coderaiser/cloudcmd:latest-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
#      - ~:/root
      - project:/mnt/fs
     
volumes:
   portainer:
   pgadmin4:
   postgres:
   redis:
   var:
   project:
   

