version: '3.2'
services:
  lizmap:
    image: jancelin/docker-lizmap:3.2rc4
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - /home/sig/qgis:/home
     - /home/sig/var:/var/www/websig/lizmap/var
    depends_on:
      - postgis
      - qgiserver
      - redisD
    links:
     - qgiserver:qgiserver
     - redisD:redisD
    entrypoint: >
      bash -c "apt-get update &&
               apt-get install -y wget &&
               wget -N -P /var/www/websig/lizmap/var/config/ https://cartman.sig.inra.fr/geopoppy/data/lizmapConfig.ini.php
               wget https://cartman.sig.inra.fr/geopoppy/data/geopoppy_pc.zip &&
               unzip geopoppy_pc.zip -d /home &&
               /start.sh"
  qgiserver:
    image: jancelin/qgis-server:2.18LTR
    restart: always
    volumes:
      - /home/sig/qgis:/home
    expose:
      - 80
      
  redisD:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    expose:
      - 6379

  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    expose:
      - 5432
    entrypoint: >
      bash -c "wget -N -P / https://raw.githubusercontent.com/jancelin/docker-postgis/master/setup-database.sh &&
               wget -N -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.tar &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.tar
    volumes:
      - /home/sig/postgres:/var/lib/postgresql
    restart: always
      
#  pgadmin4:
#    image: chorss/docker-pgadmin4
#    restart: always
#    ports:
#      - 5050:5050
#    volumes:
#      - /home/sig/postgres:/data
      
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - /home/sig/pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=jancelin@inra.fr
      - PGADMIN_DEFAULT_PASSWORD=geopoppy
      
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer:/data
     
  cloud:
    image: coderaiser/cloudcmd:latest-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
#      - ~:/root
      - /home/sig:/mnt/fs
     
volumes:
   portainer:
   redis:
   

