version: '2'
services:
     
  postgiscollec:
    image: jancelin/geopoppy:postgiscollec-0.3
    restart: always
#    ports:
#     - "5433:5432"
    expose:
      - 5432
    volumes:
#          Pensez a installer le dossier des data avant !!!!

     - "/home/pirate/collec/postgres_data_collec:/var/lib/postgresql"
       
  collec:
    image: jancelin/geopoppy:collec-0.3
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - postgiscollec:postgiscollec
      
# Collec est accessible Ã  cette adresse: https://mon_ip/collec-master
# Login: admindemo
# Password: admin_007
